"""
EmbeddingService Interface

Provider-agnostic interface for embedding services.
"""

from typing import List
from abc import ABC, abstractmethod


class EmbeddingService(ABC):
    """
    Abstract interface for embedding services.
    
    All embedding providers must implement this interface.
    """

    @abstractmethod
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        
        Args:
            text: Text to generate embedding for
            
        Returns:
            Embedding vector as list of floats
            
        Raises:
            ValueError: If text is invalid (empty, too long)
            Exception: If embedding generation fails
        """
        pass

    @abstractmethod
    def generate_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generate embeddings for multiple texts (batch).
        
        Args:
            texts: List of texts to generate embeddings for
            
        Returns:
            List of embedding vectors
            
        Raises:
            ValueError: If any text is invalid
            Exception: If embedding generation fails
        """
        pass

    @abstractmethod
    def get_dimensions(self) -> int:
        """
        Get the dimension of embeddings generated by this service.
        
        Returns:
            Number of dimensions in the embedding vector
        """
        pass

    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Get provider name.
        
        Returns:
            Provider name (e.g., "openai", "cohere", "huggingface")
        """
        pass
